# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '6.3.9.dev0+g4829b08.d20230807'
__version_tuple__ = version_tuple = (6, 3, 9, 'dev0', 'g4829b08.d20230807')
