# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '6.5.2.dev0+g582f5b8.d20230813'
__version_tuple__ = version_tuple = (6, 5, 2, 'dev0', 'g582f5b8.d20230813')
