# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '5.0.4.dev0+g2c333c8.d20221101'
__version_tuple__ = version_tuple = (5, 0, 4, 'dev0', 'g2c333c8.d20221101')
