#!/bin/bash
#SBATCH --nodes=1             # Number of nodes 
#SBATCH -A jsy@v100
#SBATCH --qos=qos_gpu-t3
#SBATCH --gres=gpu:1         # Allocate 4 GPUs per node
#SBATCH -C v100-32g

#SBATCH --job-name=VollSeg                # Jobname 
#SBATCH --cpus-per-task=40
#SBATCH --output=voll.o%j            # Output file 
#SBATCH --error=voll.o%j            # Error file 
#SBATCH --time=20:00:00       # Expected runtime HH:MM:SS (max 100h)
module purge # purging modules inherited by default

module load anaconda-py3/2020.11
#conda init bash # deactivating environments inherited by default
conda deactivate
conda activate genie
set -x # activating echo of
srun python -u Mari_genie_gt.py
